Shop_Category_Restriction:
  enabled: false
  categories: [ blocks, armor, food ] #list the shop categories to only apply boost to

Shop_Item_Restriction:
  enabled: false
  items: #list the shop items to only apply boost to format: 'category:id...'
    - "blocks:1,4,5,9,10"
    - "ores:3,5"